# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='journey_type',
            field=models.CharField(choices=[('SS', 'Single Story'), ('JS', 'Journey Story')], default='SS', max_length=2),
        ),
    ]
